language: python
sudo: false
notifications:
    email: change

python:
    - 3.5
    - 3.6
    - 3.7

env:
    - LINTING=1
    - NUMBA=0
    - NUMBA=1 COVERAGE=1
    - DOCTEST=1

before_install:
    - python -m pip install --upgrade pip
    - if [ "${LINTING}" == "1" ]; then
          pip install flake8;
      fi
    - if [ "${COVERAGE}" == "1" ]; then
          pip install coverage coveralls codecov pytest pytest-cov;
      fi
    - if [ "${NUMBA}" == "1" ]; then
          pip install numba;
      fi

install:
    - if [ "${NUMBA}" ]; then
          pip install -e .[numba];
      elif [ "${DOCTEST}" ]; then
          pip install -e .[doc];
      else
          pip install -e .;
      fi

script:
    - |
      if [ "${LINTING}" == "1" ]; then
          flake8 snf;
      else
          if [ "${COVERAGE}" == "1" ]; then
              TEST_ARGS="--cov-report term-missing --cov=snf";
          fi
          if [ "DOCTEST" == "1" ]; then
              cd docs;
              make html;
              make doctest;
              cd ..;
          fi
          py.test ${TEST_ARGS} snf;
      fi

after_success:
    - if [ "${COVERAGE}" == "1" ]; then
          coveralls; codecov;
      fi
